### ISSUE TITLE
Sometimes not formatting

### ISSUE THREAD

**Issue by mudgen** [prettier-solidity/prettier-plugin-solidity#340] opened 2020-09-21 04:34 UTC
I got to one sol file and make a change and save and the file is auto formatted.
Then I got to another sol file right next to the first one and make a change and save but the file does not auto format.   

Any idea why some files format and some don't?

**Comment by fvictorio** [comment] 2020-09-21 10:57
Hi @mudgen. We'll need more information than that to be able to help. What editor are you using? How is it configured?

**Comment by mudgen** [comment] 2020-09-21 12:19
@fvictorio thanks.

I am using VS Code.  It is configured according to the instructions given here: https://github.com/prettier-solidity/prettier-plugin-solidity#vscode

Here is the code that won't format:

```Solidity
// SPDX-License-Identifier: MIT
pragma solidity 0.7.1;

library LibDiamondStorage {
    bytes32 constant DIAMOND_STORAGE_POSITION = keccak256("diamond.standard.diamond.storage");

    struct DiamondStorage {
        // owner of the contract
        address contractOwner;
        // maps function selectors to the facets that execute the functions.
        // and maps the selectors to the slot in the selectorSlots array.
        // and maps the selectors to the position in the slot.
        // func selector => address facet, uint32 slotIndex, uint64 slotsIndex
        mapping(bytes4 => bytes32) facets;
        // array of slots of function selectors.
        // each slot holds 8 function selectors.
        mapping(uint256 => bytes32) selectorSlots;
        // The number of function selectors in selectorSlots
        uint256 selectorCount;
        // Used to query if a contract implements an interface.
        // Used to implement ERC-165.
        mapping(bytes4 => bool) supportedInterfaces;
    }

    function diamondStorage() internal pure returns (DiamondStorage storage ds) {
        bytes32 position = DIAMOND_STORAGE_POSITION;        
        assembly {
            ds.slot := position
        }        
    }
}
```

However if I comment out the assembly then the code will format.   So it seems that the assembly is causing the formatter to break.

**Comment by fvictorio** [comment] 2020-09-21 12:31
Yes, this was fixed in the latest version. Try upgrading `prettier-plugin-solidity` and see if that fixes it.

**Comment by mudgen** [comment] 2020-09-21 12:50
Thanks. I think I have the latest version: 1.0.0-alpha.57

**Comment by fvictorio** [comment] 2020-09-21 13:17
Oh, I think the problem is that https://github.com/juanfranblanco/vscode-solidity is using `alpha.55`. You should check if it can be configured to use the locally installed version, or else send a PR to them to update it.

I'm closing this because I think there's nothing we can do here, but please re-open if you think there's something we should do.

**Closed by fvictorio** 2020-09-21 13:17 UTC
