### ISSUE TITLE
End line added to Solidity code blocks in Markdown files

### ISSUE THREAD

**Issue by paulrberg** [prettier-solidity/prettier-plugin-solidity#764] opened 2022-11-27 11:51 UTC
## Description

This is exactly the same issue as https://github.com/prettier/prettier-vscode/issues/624, but none of the workarounds mentioned there work for `prettier-plugin-solidity`.

## Current Behavior

`prettier-plugin-solidity` adds an extra new line in Solidity code blocks in Markdown files. For instance, take this simple script:

\```solidity
import "./Foo.sol";
\```

An extra new line will be added on the second line, turning the script into this:

\```solidity
import "./Foo.sol";

\```

## Expected Behavior

I would prefer `prettier-plugin-solidity` not to add an extra line in Markdown code blocks. Even better, not to apply any formatting rules (by letting me disable them), because I may want to explicitly avoid many of the usual formatting rules in presentational code snippets.

## Environment

- prettier v2.8.0
- prettier-plugin-solidity v1.0.0

And this is my Prettier configuration:

```yml
bracketSpacing: true
printWidth: 120
proseWrap: "always"
singleQuote: false
tabWidth: 2
trailingComma: "all"
useTabs: false
```

**Comment by fvictorio** [comment] 2022-11-27 14:32
> Even better, not to apply any formatting rules (by letting me disable them), because I may want to explicitly avoid many of the usual formatting rules in presentational code snippets.

Does [this](https://prettier.io/docs/en/ignore.html#markdown) work for that?

The part about the extra empty line is curious, thanks for reporting it.

**Comment by Janther** [comment] 2022-11-28 06:41
How exactly are you running prettier?
I tried a small document and the command line only formats the markdown, not the embedded solidity code.

**Comment by paulrberg** [comment] 2022-11-28 09:18
> Does [this](https://prettier.io/docs/en/ignore.html#markdown) work for that?

Ah, I didn't know about the `<!-- prettier-ignore -->` trick, thanks @fvictorio.

> How exactly are you running prettier?

1. Via `OPTION+SHIFT+F` in VSCode.
2. Via `CMD+S` in VSCode (I have `formatOnSave` enabled).
3. Via the terminal

In all cases, the extra line gets added in the code snippet.

It might be worth noting that I also have EditorConfig configured in VSCode - here's a link to my [`.editorconfig`](https://github.com/paulrberg/hardhat-template/blob/ce4d8050c84e9ab9fdb32ed8abb3ac401b846874/.editorconfig) file, which includes this setting:

```text
insert_final_newline = true
```

**Comment by paulrberg** [comment] 2022-11-28 10:44
Actually, on second thoughts, this might not be caused by `prettier-plugin-solidity`.

The fact that the code is auto-formatted to have 2 spaces instead of 4 spaces means that the `tabWidth` rule specified in my [Prettier config](https://github.com/paulrberg/hardhat-template/blob/ce4d8050c84e9ab9fdb32ed8abb3ac401b846874/.prettierrc.yml) are not respected.

Could this be Prettier applying the Markdown rules for the code snippets?

**Comment by fvictorio** [comment] 2022-11-29 06:24
This is definitely a bug, but I don't think it's our fault. If I format a Solidity file, I get the right output, but if I format a markdown file with a snippet of solidity, I also get a bogus newline at the end. I don't have an `.editorconfig` in the directory were I'm testing this, so that's not involved.
 
> Could this be Prettier applying the Markdown rules for the code snippets?

I think what's happening is that prettier doens't apply your overriden config (see https://github.com/prettier/prettier/issues/5378). It kind of makes sense, because the override is talking about "files that end in `*.sol`", and a markdown snippet doesn't have an extension. Ideally prettier would support language-based overrides, not only filename-based, but that doesn't seem to be possible at the moment :disappointed:

As a workaround, you can add an override for `*.md` files, but that won't let you configure, say, different tab widths for solidity and typescript snippets.

**Comment by fvictorio** [comment] 2022-11-29 06:32
Opened https://github.com/prettier/prettier/issues/13914 in the Prettier repo.

**Comment by paulrberg** [comment] 2022-11-29 10:16
Thanks for digging this, @fvictorio. I will resort to using the `<!-- prettier-ignore -->` trick until this is solved on Prettier's end. I definitely don't want to change the formatting rules for Markdown content itself.

**Comment by fvictorio** [comment] 2022-11-29 12:55
Makes sense! I'm going to close this one then. I'll try to comment here if the issue is solved in Prettier core.

**Closed by fvictorio** 2022-11-29 12:55 UTC

**Comment by paulrberg** [comment] 2022-11-29 20:27
Thanks @fvictorio. Nitpick though - shouldn't this have been closed as "not planned" rather than "completed"? Future visitors might get confused.

**Comment by fvictorio** [comment] 2022-12-05 10:53
@paulrberg you are right, I always forget about that GitHub feature :sweat_smile:

That being said, @Janther found a clever workaround that actually fixes this, so this will actually be fixed in the next version :tada:

**Comment by paulrberg** [comment] 2022-12-05 11:19
So cool.
