### ISSUE TITLE
failed to parse buffer.

### ISSUE THREAD

**Issue by TimDaub** [prettier-solidity/prettier-plugin-solidity#536] opened 2021-06-15 09:00 UTC
When I try to run `:Prettier` on a .sol file, I get `failed to parse buffer. `. I manually run `yarn` in `.vim/plugged/vim-prettier`, I get the output:

```bash
yarn install
yarn install v1.22.10
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > prettier-plugin-solidity@1.0.0-beta.13" has incorrect peer dependency "prettier@^2.3.0".
[4/4] 🔨  Building fresh packages...
✨  Done in 7.33s.
```

I then updated `prettier` to the latest version

```bash
prettier -v
2.3.1
```

I also tried using an earlier release by modifying the vim-plug configuration to install `yarn add prettier-plugin-solidity@v1.0.0-beta.12`. No change.

My `.vimrc` is:

```
call plug#begin('~/.vim/plugged')
Plug 'prettier/vim-prettier', {
  \ 'do': 'yarn install && yarn add prettier-plugin-solidity@v1.0.0-beta.12',
  \ 'branch': 'release/1.x',
  \ 'for': [
    \ 'javascript',
    \ 'typescript',
    \ 'css',
    \ 'less',
    \ 'scss',
    \ 'json',
    \ 'graphql',
    \ 'markdown',
    \ 'vue',
    \ 'lua',
    \ 'php',
    \ 'python',
    \ 'ruby',
    \ 'html',
    \ 'swift',
    \ 'solidity'] }
call plug#end()

let g:prettier#exec_cmd_path = '~/.vim/bundle/vim-prettier/node_modules/.bin/prettier'
```

I then adjusted `let g:prettier#exec_cmd_path` as outlined in #537. Now, for a valid `.sol` file:

```solidity
pragma solidity ^0.6.7;
```

```
src/Honeybatcher.sol|1 col 8| Unexpected token, expected ";"
Prettier: failed to parse buffer
```

**Edit:**

It may be that prettier-plugin-solidity cannot be used with the `:Prettier` command. I have the following contract

```solidity
// @format
pragma solidity ^0.6.7;

import "ds-token/token.sol";
import "./StateTree.sol";

contract Honeybatcher {StateTree public tree;
}
```

And I run prettier on saving the file `:w`, then `StateTree` is appropriately put into the next line. However, when I try to fix the same file using `:Prettier`, I get the above described error.

**Comment by Janther** [comment] 2021-06-15 10:32
I'd like to specify that the problem is likely related to vim and the plugin's installation there.
he contract is properly formatted when I run the plugin in node.

**Comment by TimDaub** [comment] 2021-06-15 16:07
I followed some advice by Franco Victorio on Telegram where he told me that I should adjust the version number of "prettier" to "^2.3.1" in `.vim/plugged/vim-prettier`. And then update the dependencies via `yarn` in the same directory. It didn't help, unfortunately.

**Comment by TimDaub** [comment] 2021-06-15 16:26
Interesting, I managed to make it work partially. Instead of using vim-prettier, I now did the following:

- I installed both dependencies globally `npm i -g prettier prettier-plugin-solidity` after having [read](https://prettier.io/docs/en/plugins.html#using-plugins) that:

> Prettier expects each of pluginSearchDirs to contain node_modules subdirectory, where @prettier/plugin-*, @*/prettier-plugin-* and prettier-plugin-* will be searched. For instance, this can be your project directory or the location of global npm modules.

Then, I looked into creating a mapping to invoke the globally installed prettier in vim and [found something](https://prettier.io/docs/en/vim.html#running-manually):

```
nnoremap gp :silent %!prettier --stdin-filepath %<CR>
```

Now, every time I open a Solidity file in vim and press `gp` in normal mode, the files adjust.

There's one thing that I noticed that may also have lead to the problem. In the vim section of this repository's readme.md, we enable "solidity" in "for" of the "vim-plug" configuration. However, for my globally working prettier installation, solidity's parser is called "solidity-parse". Could it have something to do with the problem?

```bash
  --parser <flow|babel|babel-flow|babel-ts|typescript|espree|meriyah|css|less|scss|json|json5|json-stringify|graphql|markdown|mdx|vue|y
aml|glimmer|html|angular|lwc|solidity-parse>
```

**Comment by TimDaub** [comment] 2021-06-15 16:39
I digged some more. I installed vim-prettier as a pathogen plugin and then installed prettier-plugin-solidity in that directory and changed the version of `prettier` to 2.3.1, now I can do:

```bash
~/.vim/bundle/vim-prettier/node_modules/.bin/prettier --list-different src/**/*.s
ol
src/StateTree.sol
src/StateTree.t.sol
```

so the binary seemed to have worked. Because of that, I went ahead and set it in my .vimrc

let g:prettier#exec_cmd_path = '~/.vim/bundle/vim-prettier/node_modules/.bin/prettier'

I then open vim and do: `:PrettierCliPath`:

`/Users/user/.vim/bundle/vim-prettier/node_modules/.bin/prettier`

however, same problem as above. failed to parse buffer.

**Comment by anajuliabit** [comment] 2022-07-06 01:12
Having the same issue. Did you found a solution @TimDaub?

**Comment by TimDaub** [comment] 2022-07-06 07:46
yeah my solution is to not use this plugin 😅🥺

**Comment by fvictorio** [comment] 2022-10-25 10:10
For the record: I use vim and the plugin works for me. My setup is something like this:

- `vim-plug`
- `Plug 'prettier/vim-prettier', { 'do': 'npm install && npm install prettier-plugin-solidity', 'branch': 'release/1.x', 'for': ['javascript', 'typescript', 'json', 'solidity', 'html', 'css', 'typescript.tsx', 'markdown', 'xml'] }` in my `.vimrc`

I don't think I needed to do anything else.

I'm going to close this one for bookkeeping reasons. If someone has an issue with making vim+prettier-solidity work, please open a new one and I'll try to help.

**Closed by fvictorio** 2022-10-25 10:10 UTC
Labels: question

**Comment by fabrice-quadrata** [comment] 2023-12-15 01:54
same issue here
