### ISSUE TITLE
Switch statements in assembly break formatting

### ISSUE THREAD

**Issue by jacobwis** [prettier-solidity/prettier-plugin-solidity#591] opened 2021-09-28 11:47 UTC
Hello,

I've noticed any time I use a switch statement when writing inline assembly, prettier stops working altogether. I've tried both VSCode and CLI, so I know it's not my editor.

Heres the error prettier displays:

```
Error: Should never reach here
	at ASTBuilder.visitAssemblyLiteral (/Users/user/Documents/projects/project/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/dist/index.cjs.js:36514:11)
	at ASTBuilder.visitAssemblyCase (/Users/user/Documents/projects/project/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/dist/index.cjs.js:36527:20)
	at /Users/user/Documents/projects/project/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/dist/index.cjs.js:36520:49
	at Array.map (<anonymous>)
	at ASTBuilder.visitAssemblySwitch (/Users/user/Documents/projects/project/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/dist/index.cjs.js:36520:33)
	at AssemblySwitchContext.accept (/Users/user/Documents/projects/project/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/dist/index.cjs.js:34710:22)
	at ASTBuilder.visit (/Users/user/Documents/projects/project/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/dist/index.cjs.js:17669:19)
	at ASTBuilder.visitAssemblyItem (/Users/user/Documents/projects/project/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/dist/index.cjs.js:36469:17)
	at /Users/user/Documents/projects/project/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/dist/index.cjs.js:36434:62
	at Array.map (<anonymous>)
	at ASTBuilder.visitAssemblyBlock (/Users/user/Documents/projects/project/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/dist/index.cjs.js:36434:43)
	at ASTBuilder.visitInlineAssemblyStatement (/Users/user/Documents/projects/project/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/dist/index.cjs.js:36429:18)
	at InlineAssemblyStatementContext.accept (/Users/user/Documents/projects/project/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/dist/index.cjs.js:33686:22)
	at ASTBuilder.visit (/Users/user/Documents/projects/project/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/dist/index.cjs.js:17669:19)
	at ASTBuilder.visitStatement (/Users/user/Documents/projects/project/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/dist/index.cjs.js:35446:17)
	at /Users/user/Documents/projects/project/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/dist/index.cjs.js:35482:51
	at Array.map (<anonymous>)
	at ASTBuilder.visitBlock (/Users/user/Documents/projects/project/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/dist/index.cjs.js:35482:35)
	at ASTBuilder.visitFunctionDefinition (/Users/user/Documents/projects/project/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/dist/index.cjs.js:35521:20)
	at FunctionDefinitionContext.accept (/Users/user/Documents/projects/project/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/dist/index.cjs.js:32561:22)
	at ASTBuilder.visit (/Users/user/Documents/projects/project/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/dist/index.cjs.js:17669:19)
	at ASTBuilder.visitContractPart (/Users/user/Documents/projects/project/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/dist/index.cjs.js:35334:17)
	at ContractPartContext.accept (/Users/user/Documents/projects/project/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/dist/index.cjs.js:32232:22)
	at ASTBuilder.visit (/Users/user/Documents/projects/project/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/dist/index.cjs.js:17669:19)
	at /Users/user/Documents/projects/project/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/dist/index.cjs.js:35344:52
	at Array.map (<anonymous>)
	at ASTBuilder.visitContractDefinition (/Users/user/Documents/projects/project/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/dist/index.cjs.js:35344:36)
	at ContractDefinitionContext.accept (/Users/user/Documents/projects/project/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/dist/index.cjs.js:32152:22)
	at ASTBuilder.visit (/Users/user/Documents/projects/project/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/dist/index.cjs.js:17669:19)
	at /Users/user/Documents/projects/project/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/dist/index.cjs.js:35327:59
	at Array.map (<anonymous>)
	at ASTBuilder.visitSourceUnit (/Users/user/Documents/projects/project/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/dist/index.cjs.js:35327:39)
	at SourceUnitContext.accept (/Users/user/Documents/projects/project/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/dist/index.cjs.js:31855:22)
	at ASTBuilder.visit (/Users/user/Documents/projects/project/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/dist/index.cjs.js:17669:19)
	at Object.parse (/Users/user/Documents/projects/project/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/dist/index.cjs.js:36857:14)
	at Object.parse (/Users/user/Documents/projects/project/node_modules/prettier-plugin-solidity/src/parser.js:18:25)
	at Object.parse$a [as parse] (/Users/user/Documents/projects/project/node_modules/prettier/index.js:12513:19)
	at coreFormat (/Users/user/Documents/projects/project/node_modules/prettier/index.js:14044:16)
	at formatWithCursor$1 (/Users/user/Documents/projects/project/node_modules/prettier/index.js:14284:14)
	at /Users/user/Documents/projects/project/node_modules/prettier/index.js:59304:12
	at Object.format (/Users/user/Documents/projects/project/node_modules/prettier/index.js:59324:12)
	at t.default.<anonymous> (/Users/user/.vscode/extensions/esbenp.prettier-vscode-9.0.0/dist/extension.js:1:14671)
	at Generator.next (<anonymous>)
	at s (/Users/user/.vscode/extensions/esbenp.prettier-vscode-9.0.0/dist/extension.js:1:7872)
```

**Comment by fvictorio** [comment] 2022-10-25 10:05
Closing for lack of reproduction steps, and because I think it's likely that a boolean literal was used here, which will be fixed by #750.

**Closed by fvictorio** 2022-10-25 10:05 UTC
Labels: bug
