### ISSUE TITLE
Enum aligning 

### ISSUE THREAD

**Issue by avatar-lavventura** [prettier-solidity/prettier-plugin-solidity#362] opened 2020-10-15 21:42 UTC
After running prettier on the following code:

```
library Lib {
    enum CacheType {
        PUBLIC, 
        PRIVATE 
    }
}
```

I get:

```
library Lib {
    enum CacheType {
                    PUBLIC, 
                    PRIVATE 
    }
}
```

Originally there was 4 spaces before each `enum` , like in any `struct`. But `prettier` carries them to the beginning of `{`. Would be possible to force `prettier` to do spacing like it does in `struct`.

**Comment by fvictorio** [comment] 2020-11-08 21:46
I can't reproduce this, how are you running prettier and what options are enabled?

**Comment by fvictorio** [comment] 2020-11-10 10:39
Closing this, but please re-open if it's still happening.

**Closed by fvictorio** 2020-11-10 10:39 UTC

**Comment by avatar-lavventura** [comment] 2020-11-10 22:35
Sorry for the late reply:
```
$ cat .prettierrce
{
  "overrides": [
    {
      "files": "contracts/**/*.sol",
      "options": {
        "printWidth": 120,
        "tabWidth": 4,
        "useTabs": false,
        "singleQuote": false,
        "bracketSpacing": false,
        "explicitTypes": "always"
      }
    }
  ]
}
```

**Comment by fvictorio** [comment] 2020-11-11 11:36
Sorry, you mean it keeps happening? Which version of node, prettier and prettier-plugin-solidity are you using?
